title: out.of.desk
description: My Filtered Online Notepad
author: Gaurav Ramesh
github: https://github.com/ggauravr
about:
disqus_shortname: outofdesk
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

# collections:
#   project:
#     output: true
#     permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/out.of.desk/"
    # - icon: fa-twitter
    #   link: "#"
    # - icon: fa-linkedin
    #   link: "#"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/ggauravr"
    - icon: fa-instagram
      link: "https://instagram.com/out.of.desk/"

# share:
#   twitter_username: github.io
#   fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://ggauravr.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
